"""
This type stub file was generated by pyright.
"""

"""
Tsu bot responds to all queries with a Sun Tsu sayings

Quoted from Sun Tsu's The Art of War
Translated by LIONEL GILES, M.A. 1910
Hosted by the Gutenberg Project
https://www.gutenberg.org/
"""
pairs = ...
suntsu_chatbot = ...
def suntsu_chat(): # -> None:
    ...

def demo(): # -> None:
    ...

if __name__ == "__main__":
    ...
