"""
This type stub file was generated by pyright.
"""

from nltk.misc.babelfish import babelize_shell
from nltk.misc.chomsky import generate_chomsky
from nltk.misc.minimalset import MinimalSet
from nltk.misc.wordfinder import word_finder
