---
dev_addr: 127.0.0.1:8888
site_url: https://sandbox_agent.readthedocs.io
repo_url: https://github.com/bossjones/sandbox_agent
site_author: bossjones
site_description: POC langchain rag discord chatbot. Heavily inspired by DiscordLangAgent
repo_name: bossjones/sandbox_agent
site_name: GoobAI Documentation
copyright: MIT License - Copyright (c) 2024 bossjones
edit_uri: edit/main/docs
watch: [src/]
extra_css: [css/mkdocstrings.css]
theme:
  locale: en
  name: material
    # features: [content.code.copy, content.code.select, navigation.footer]
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.select  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-selection-button
    - content.tooltips
    - navigation.footer
    - search.share
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - autorefs  # recommended by mkdocstrings
  - mermaid2
  - mkdocstrings:  # https://mkdocstrings.github.io/
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
            - https://mkdocstrings.github.io/autorefs/objects.inv
            # paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ['!^_']
            heading_level: 1
            inherited_members: false
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
      default_handler: python
  - search  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  - tags  # https://squidfunk.github.io/mkdocs-material/plugins/tags/
    # Want to have ezlinks after macros
    # because macros might return markup with ezlinks that we want expanded - e.g.: for people
    # - ezlinks  # https://github.com/orbikm/mkdocs-ezlinks-plugin
nav:
  - Home: index.md
  # - Images: images.md
  - Versioning: versioning.md
  # - Hardware: hardware.md
  # - Firmware: firmware.md
  # - Python Interface: controller.md
  # - GUI: gui.md
  - Changelog: changelog.md
  - Developer Guide: dev.md
  - Acknowledgement: acknowledgement.md
  - Utilities: utilities.md
markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true

  # Python Markdown Extensions
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink  # Allows plain ol' URLs to be links
  - pymdownx.snippets
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:mermaid2.fence_mermaid_custom
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
