"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...utils import is_torch_available

_import_structure = ...
if not is_torch_available():
    ...
if TYPE_CHECKING:
    ...
else:
    ...
