"""
This type stub file was generated by pyright.
"""

import contextlib
import http.client as httplib
import urllib3.connection as conn
import urllib3.connectionpool as cpool

"""Utilities for patching in cassettes"""
log = ...
_HTTPConnection = httplib.HTTPConnection
_HTTPSConnection = httplib.HTTPSConnection
cpool = ...
conn = ...
class CassettePatcherBuilder:
    def __init__(self, cassette) -> None:
        ...

    def build(self): # -> chain[tuple[Any, Literal['HTTPConnection'], type[VCRHTTPConnection]] | tuple[Any, Literal['HTTPSConnection'], type[VCRHTTPSConnection]] | _patch[dict[Any, Any] | Any] | ConnectionRemover | tuple[Any, Literal['ConnectionCls'], type[VCRRequestsHTTPConnection]] | tuple[Any, Literal['ConnectionCls'], type[VCRRequestsHTTPSConnection]] | tuple[Any, Literal['HTTPConnectionWithTimeout'], type[VCRHTTPConnectionWithTimeout]] | tuple[Any, Literal['HTTPSConnectionWithTimeout'], type[VCRHTTPSConnectionWithTimeout]] | tuple[Any, Literal['SCHEME_TO_CONNECTION'], dict[str, Any]] | tuple[type[SimpleAsyncHTTPClient], Literal['fetch_impl'], _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | None]] | tuple[type[CurlAsyncHTTPClient], Literal['fetch_impl'], _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | None]] | tuple[type[ClientSession], Literal['_request'], _Wrapped[Callable[..., Any], Any, Callable[..., Any], Coroutine[Any, Any, MockClientResponse | ClientResponse]]] | tuple[type[AsyncClient], Literal['_send_single_request'], _Wrapped[Callable[..., Any], Any, Callable[..., Any], Coroutine[Any, Any, Any]]] | tuple[type[Client], Literal['_send_single_request'], _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]]:
        ...



class ConnectionRemover:
    def __init__(self, connection_class) -> None:
        ...

    def add_connection_to_pool_entry(self, pool, connection): # -> None:
        ...

    def __enter__(self): # -> Self:
        ...

    def __exit__(self, *args): # -> None:
        ...



def reset_patchers(): # -> Generator[_patch[_HTTPConnection] | _patch[_HTTPSConnection] | _patch[_VerifiedHTTPSConnection] | _patch[_connHTTPConnection] | _patch[_connHTTPSConnection] | _patch[Any] | _patch[_HTTPConnectionWithTimeout] | _patch[_HTTPSConnectionWithTimeout] | _patch[Callable[..., None]], Any, None]:
    ...

@contextlib.contextmanager
def force_reset(): # -> Generator[None, Any, None]:
    ...
