"""
This type stub file was generated by pyright.
"""

CASSETTE_FORMAT_VERSION = ...
def deserialize(cassette_string, serializer): # -> tuple[list[Request], list[Any]]:
    ...

def serialize(cassette_dict, serializer):
    ...
