"""
This type stub file was generated by pyright.
"""

import unittest

class VCRMixin:
    """A TestCase mixin that provides VCR integration."""
    vcr_enabled = ...
    def setUp(self): # -> None:
        ...



class VCRTestCase(VCRMixin, unittest.TestCase):
    ...
