"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader.api import *
from nltk.corpus.reader.util import *
from nltk.tokenize import *

"""
Read from the Senseval 2 Corpus.

SENSEVAL [http://www.senseval.org/]
Evaluation exercises for Word Sense Disambiguation.
Organized by ACL-SIGLEX [https://www.siglex.org/]

Prepared by Ted Pedersen <tpederse@umn.edu>, University of Minnesota,
https://www.d.umn.edu/~tpederse/data.html
Distributed with permission.

The NLTK version of the Senseval 2 files uses well-formed XML.
Each instance of the ambiguous words "hard", "interest", "line", and "serve"
is tagged with a sense identifier, and supplied with context.
"""
class SensevalInstance:
    def __init__(self, word, position, context, senses) -> None:
        ...

    def __repr__(self): # -> str:
        ...



class SensevalCorpusReader(CorpusReader):
    def instances(self, fileids=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...



class SensevalCorpusView(StreamBackedCorpusView):
    def __init__(self, fileid, encoding) -> None:
        ...

    def read_block(self, stream): # -> list | list[SensevalInstance]:
        ...
