"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader.api import *
from nltk.corpus.reader.util import *

class SwitchboardTurn(list):
    """
    A specialized list object used to encode switchboard utterances.
    The elements of the list are the words in the utterance; and two
    attributes, ``speaker`` and ``id``, are provided to retrieve the
    spearker identifier and utterance id.  Note that utterance ids
    are only unique within a given discourse.
    """
    def __init__(self, words, speaker, id) -> None:
        ...

    def __repr__(self): # -> str:
        ...



class SwitchboardCorpusReader(CorpusReader):
    _FILES = ...
    def __init__(self, root, tagset=...) -> None:
        ...

    def words(self): # -> StreamBackedCorpusView:
        ...

    def tagged_words(self, tagset=...): # -> StreamBackedCorpusView:
        ...

    def turns(self): # -> StreamBackedCorpusView:
        ...

    def tagged_turns(self, tagset=...): # -> StreamBackedCorpusView:
        ...

    def discourses(self): # -> StreamBackedCorpusView:
        ...

    def tagged_discourses(self, tagset=...): # -> StreamBackedCorpusView:
        ...

    _UTTERANCE_RE = ...
    _SEP = ...
