"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader.api import *
from nltk.corpus.reader.util import *

"""
Module for reading, writing and manipulating
Toolbox databases and settings fileids.
"""
class ToolboxCorpusReader(CorpusReader):
    def xml(self, fileids, key=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...

    def fields(self, fileids, strip=..., unwrap=..., encoding=..., errors=..., unicode_fields=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...

    def entries(self, fileids, **kwargs): # -> list:
        ...

    def words(self, fileids, key=...): # -> list[Any | str | Element]:
        ...



def demo(): # -> None:
    ...

if __name__ == "__main__":
    ...
