"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader.api import *
from nltk.corpus.reader.bracket_parse import BracketParseCorpusReader
from nltk.corpus.reader.tagged import TaggedCorpusReader
from nltk.corpus.reader.util import *

"""
Corpus reader for the York-Toronto-Helsinki Parsed Corpus of Old
English Prose (YCOE), a 1.5 million word syntactically-annotated
corpus of Old English prose texts. The corpus is distributed by the
Oxford Text Archive: http://www.ota.ahds.ac.uk/ It is not included
with NLTK.

The YCOE corpus is divided into 100 files, each representing
an Old English prose text. Tags used within each text complies
to the YCOE standard: https://www-users.york.ac.uk/~lang22/YCOE/YcoeHome.htm
"""
class YCOECorpusReader(CorpusReader):
    """
    Corpus reader for the York-Toronto-Helsinki Parsed Corpus of Old
    English Prose (YCOE), a 1.5 million word syntactically-annotated
    corpus of Old English prose texts.
    """
    def __init__(self, root, encoding=...) -> None:
        ...

    def documents(self, fileids=...): # -> list[str | Any]:
        """
        Return a list of document identifiers for all documents in
        this corpus, or for the documents with the given file(s) if
        specified.
        """
        ...

    def fileids(self, documents=...): # -> list[str | Any] | list | Any:
        """
        Return a list of file identifiers for the files that make up
        this corpus, or that store the given document(s) if specified.
        """
        ...

    def words(self, documents=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...

    def sents(self, documents=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...

    def paras(self, documents=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...

    def tagged_words(self, documents=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...

    def tagged_sents(self, documents=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...

    def tagged_paras(self, documents=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...

    def parsed_sents(self, documents=...): # -> str | ConcatenatedCorpusView | LazyConcatenation | list | tuple[()] | Element:
        ...



class YCOEParseCorpusReader(BracketParseCorpusReader):
    """Specialized version of the standard bracket parse corpus reader
    that strips out (CODE ...) and (ID ...) nodes."""
    ...


class YCOETaggedCorpusReader(TaggedCorpusReader):
    def __init__(self, root, items, encoding=...) -> None:
        ...



documents = ...
