"""
This type stub file was generated by pyright.
"""

class CassetteNotFoundError(FileNotFoundError):
    ...


class CassetteDecodeError(ValueError):
    ...


class FilesystemPersister:
    @classmethod
    def load_cassette(cls, cassette_path, serializer): # -> tuple[list[Request], list[Any]]:
        ...

    @staticmethod
    def save_cassette(cassette_path, cassette_dict, serializer): # -> None:
        ...
