"""
This type stub file was generated by pyright.
"""

SPEC_SEMTYPES = ...
OPTIONAL_RELATIONSHIPS = ...
class GlueFormula:
    def __init__(self, meaning, glue, indices=...) -> None:
        ...

    def applyto(self, arg): # -> Self:
        """self = (\\x.(walk x), (subj -o f))
        arg  = (john        ,  subj)
        returns ((walk john),          f)
        """
        ...

    def make_VariableExpression(self, name): # -> IndividualVariableExpression | FunctionVariableExpression | EventVariableExpression | ConstantExpression:
        ...

    def make_LambdaExpression(self, variable, term): # -> LambdaExpression:
        ...

    def lambda_abstract(self, other): # -> Self:
        ...

    def compile(self, counter=...):
        """From Iddo Lev's PhD Dissertation p108-109"""
        ...

    def simplify(self): # -> Self:
        ...

    def __eq__(self, other) -> bool:
        ...

    def __ne__(self, other) -> bool:
        ...

    def __lt__(self, other) -> bool:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self): # -> str:
        ...



class GlueDict(dict):
    def __init__(self, filename, encoding=...) -> None:
        ...

    def read_file(self, empty_first=...): # -> None:
        ...

    def __str__(self) -> str:
        ...

    def to_glueformula_list(self, depgraph, node=..., counter=..., verbose=...): # -> list:
        ...

    def lookup(self, node, depgraph, counter): # -> list:
        ...

    def add_missing_dependencies(self, node, depgraph): # -> None:
        ...

    def get_semtypes(self, node): # -> list[str] | list:
        """
        Based on the node, return a list of plausible semtypes in order of
        plausibility.
        """
        ...

    def get_glueformulas_from_semtype_entry(self, lookup, word, node, depgraph, counter): # -> list:
        ...

    def get_meaning_formula(self, generic, word):
        """
        :param generic: A meaning formula string containing the
            parameter "<word>"
        :param word: The actual word to be replace "<word>"
        """
        ...

    def initialize_labels(self, expr, node, depgraph, unique_index): # -> VariableExpression | ConstantExpression | ImpExpression:
        ...

    def find_label_name(self, name, node, depgraph, unique_index): # -> str:
        ...

    def get_label(self, node):
        """
        Pick an alphabetic character as identifier for an entity in the model.

        :param value: where to index into the list of characters
        :type value: int
        """
        ...

    def lookup_unique(self, rel, node, depgraph):
        """
        Lookup 'key'. There should be exactly one item in the associated relation.
        """
        ...

    def get_GlueFormula_factory(self): # -> type[GlueFormula]:
        ...



class Glue:
    def __init__(self, semtype_file=..., remove_duplicates=..., depparser=..., verbose=...) -> None:
        ...

    def train_depparser(self, depgraphs=...): # -> None:
        ...

    def parse_to_meaning(self, sentence): # -> list:
        ...

    def get_readings(self, agenda): # -> list:
        ...

    def parse_to_compiled(self, sentence): # -> list[list]:
        ...

    def dep_parse(self, sentence): # -> Generator[Any, None, None] | Iterator:
        """
        Return a dependency graph for the sentence.

        :param sentence: the sentence to be parsed
        :type sentence: list(str)
        :rtype: DependencyGraph
        """
        ...

    def depgraph_to_glue(self, depgraph): # -> list:
        ...

    def get_glue_dict(self): # -> GlueDict:
        ...

    def gfl_to_compiled(self, gfl): # -> list:
        ...

    def get_pos_tagger(self): # -> RegexpTagger:
        ...



class DrtGlueFormula(GlueFormula):
    def __init__(self, meaning, glue, indices=...) -> None:
        ...

    def make_VariableExpression(self, name): # -> DrtIndividualVariableExpression | DrtFunctionVariableExpression | DrtEventVariableExpression | DrtConstantExpression:
        ...

    def make_LambdaExpression(self, variable, term): # -> DrtLambdaExpression:
        ...



class DrtGlueDict(GlueDict):
    def get_GlueFormula_factory(self): # -> type[DrtGlueFormula]:
        ...



class DrtGlue(Glue):
    def __init__(self, semtype_file=..., remove_duplicates=..., depparser=..., verbose=...) -> None:
        ...

    def get_glue_dict(self): # -> DrtGlueDict:
        ...



def demo(show_example=...): # -> None:
    ...

if __name__ == "__main__":
    ...
