"""
This type stub file was generated by pyright.
"""

from nltk.draw.util import ColorizedList

"""
Visualization tools for CFGs.
"""
class ProductionList(ColorizedList):
    ARROW = ...


_CFGEditor_HELP = ...
class CFGEditor:
    """
    A dialog window for creating and editing context free grammars.
    ``CFGEditor`` imposes the following restrictions:

    - All nonterminals must be strings consisting of word
      characters.
    - All terminals must be strings consisting of word characters
      and space characters.
    """
    ARROW = ...
    _LHS_RE = ...
    _ARROW_RE = ...
    _PRODUCTION_RE = ...
    _TOKEN_RE = ...
    _BOLD = ...
    def __init__(self, parent, cfg=..., set_cfg_callback=...) -> None:
        ...



class CFGDemo:
    def __init__(self, grammar, text) -> None:
        ...

    def reset_workspace(self): # -> None:
        ...

    def workspace_markprod(self, production): # -> None:
        ...

    def destroy(self, *args): # -> None:
        ...

    def mainloop(self, *args, **kwargs): # -> None:
        ...



def demo2(): # -> None:
    ...

def demo(): # -> None:
    ...

def demo3(): # -> None:
    ...

if __name__ == "__main__":
    ...
