"""
This type stub file was generated by pyright.
"""

import abc
from .pycompat import ABC

class WritableStream(ABC):
    @abc.abstractmethod
    def write(self, s): # -> None:
        ...

    @classmethod
    def __subclasshook__(cls, C): # -> _NotImplementedType | Literal[True]:
        ...



file_reading_errors = ...
def shitcode(s): # -> LiteralString:
    ...

def get_repr_function(item, custom_repr): # -> Callable[[object], str]:
    ...

DEFAULT_REPR_RE = ...
def normalize_repr(item_repr): # -> str:
    """Remove memory address (0x...) from a default python repr"""
    ...

def get_shortish_repr(item, custom_repr=..., max_length=..., normalize=...): # -> str:
    ...

def truncate(string, max_length): # -> str:
    ...

def ensure_tuple(x): # -> tuple[Any, ...] | tuple[Any | Iterable[Any]]:
    ...
