"""
This type stub file was generated by pyright.
"""

from nltk.sem.logic import *

"""
Helper functions for CCG semantics computation
"""
def compute_type_raised_semantics(semantics): # -> LambdaExpression:
    ...

def compute_function_semantics(function, argument): # -> ApplicationExpression:
    ...

def compute_composition_semantics(function, argument): # -> LambdaExpression:
    ...

def compute_substitution_semantics(function, argument): # -> LambdaExpression:
    ...
