"""
This type stub file was generated by pyright.
"""

"""
Provide structured access to documentation.
"""
def brown_tagset(tagpattern=...): # -> None:
    ...

def claws5_tagset(tagpattern=...): # -> None:
    ...

def upenn_tagset(tagpattern=...): # -> None:
    ...

if __name__ == "__main__":
    ...
