"""
This type stub file was generated by pyright.
"""

from typing import Optional
from langgraph.types import PregelExecutableTask, RetryPolicy

logger = ...
def run_with_retry(task: PregelExecutableTask, retry_policy: Optional[RetryPolicy]) -> None:
    """Run a task with retries."""
    ...

async def arun_with_retry(task: PregelExecutableTask, retry_policy: Optional[RetryPolicy], stream: bool = ...) -> None:
    """Run a task asynchronously with retries."""
    ...
