---
# TODO: Enable this and make sure it works with our codebase.
# SOURCE: https://github.com/chroma-core/chroma/tree/main/.github/workflows
name: Scan for Python Vulnerabilities

on:
  workflow_call:
  # NOTE: when this is working we need to comment this out
  # You can run this with every type of event, but it's better to run it only when you actually need it.
  workflow_dispatch:
  # push:
  #   branches: [main, master]
  #   paths: [.github/labels.yml]
jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Setup
      #   uses: ./.github/actions/python
      # - uses: ./.github/actions/bandit-scan/
      #   with:
      #     input-dir: '.'
      #     format: 'json'
      #     bandit-config: 'bandit.yaml'
      #     output-file: 'bandit-report.json'
      # - name: Upload Bandit Report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: bandit-artifact
      #     path: |
      #       bandit-report.json
